name: DEPLOYMENT TO TEZOS TESTNET CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install npm libraries
        run: npm install

      # Runs a single command using the runners shell
      - name: Download Smartpy-CLI
        run: echo 'y' | bash <(curl -s https://smartpy.io/cli/install.sh)

      - name: Compile gallery smart contract
        run: npm run compile:local

      - name: List build directory
        run: ls -la build/

      - name: Test gallery smart contract
        run: npm run test:local

      - name: Estimate contract deployment cost
        run: PROTOCOL_NAME=hangzhounet HANGZHOUNET_PUBLIC_KEY=${{secrets.HANGZHOUNET_PUBLIC_KEY}} HANGZHOUNET_PRIVATE_KEY=${{secrets.HANGZHOUNET_PRIVATE_KEY}} ./scripts/tezos-utils.js estimate_github calculator

      - name: Deploy contract to hangzhounet testnet
        run: PROTOCOL_NAME=hangzhounet HANGZHOUNET_PUBLIC_KEY=${{secrets.HANGZHOUNET_PUBLIC_KEY}} HANGZHOUNET_PRIVATE_KEY=${{secrets.HANGZHOUNET_PRIVATE_KEY}} ./scripts/tezos-utils.js deploy_github calculator

